version: "3.8"

services:
  suave-mevm:
    image: flashbots/suave-geth:latest
    command:
      - --dev
      - --dev.gaslimit=30000000
      - --http
      - --http.port=8545
      - --http.addr=0.0.0.0
      - --http.vhosts=*
      - --http.corsdomain=*
      - --ws
      - --ws.origins=*
      - --ws.addr=0.0.0.0
      - --datadir=/data
      - --keystore=/keystore/keystore
      - --unlock=0xB5fEAfbDD752ad52Afb7e1bD2E40432A485bBB7F
      - --password=/keystore/password.txt
      - --suave.dev
      - --suave.eth.remote_endpoint=http://suave-enabled-chain:8545
      - --suave.eth.external-whitelist=172.17.0.1
    depends_on:
      - suave-enabled-chain
    volumes:
      - ./suave-ex-node:/keystore
    ports:
      - 8545:8545
      - 8546:8546
    networks: 
      - suave-net
  suave-enabled-chain:
    build: ../..
    command:
      - --dev
      - --dev.gaslimit=30000000
      - --http
      - --http.addr=0.0.0.0
      - --http.vhosts=*
      - --http.corsdomain=*
      - --datadir=/data
      - --keystore=/keystore/keystore
      - --password=/keystore/password.txt
      - --unlock=0xB5fEAfbDD752ad52Afb7e1bD2E40432A485bBB7F
      - --allow-insecure-unlock 
      - --ws
    ports:
      - 8555:8545
    volumes:
      - ./suave-ex-node:/keystore 
    networks:
      - suave-net
networks:
  suave-net:
